version: '3'

services:
  database:
    container_name: 'onlistdatabase'
    image: 'postgres:13-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=onlistdatabase
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
